// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by running: flutter pub run build_runner build

part of 'chat_message_entity.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class MessageSenderEntityAdapter extends TypeAdapter<MessageSenderEntity> {
  @override
  final int typeId = 0;

  @override
  MessageSenderEntity read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return MessageSenderEntity.user;
      case 1:
        return MessageSenderEntity.character;
      default:
        return MessageSenderEntity.user;
    }
  }

  @override
  void write(BinaryWriter writer, MessageSenderEntity obj) {
    switch (obj) {
      case MessageSenderEntity.user:
        writer.writeByte(0);
        break;
      case MessageSenderEntity.character:
        writer.writeByte(1);
        break;
    }
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageSenderEntityAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class MessageTypeEntityAdapter extends TypeAdapter<MessageTypeEntity> {
  @override
  final int typeId = 1;

  @override
  MessageTypeEntity read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return MessageTypeEntity.text;
      case 1:
        return MessageTypeEntity.image;
      case 2:
        return MessageTypeEntity.textWithImage;
      default:
        return MessageTypeEntity.text;
    }
  }

  @override
  void write(BinaryWriter writer, MessageTypeEntity obj) {
    switch (obj) {
      case MessageTypeEntity.text:
        writer.writeByte(0);
        break;
      case MessageTypeEntity.image:
        writer.writeByte(1);
        break;
      case MessageTypeEntity.textWithImage:
        writer.writeByte(2);
        break;
    }
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageTypeEntityAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class ChatMessageEntityAdapter extends TypeAdapter<ChatMessageEntity> {
  @override
  final int typeId = 2;

  @override
  ChatMessageEntity read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ChatMessageEntity(
      id: fields[0] as String,
      text: fields[1] as String?,
      sender: fields[2] as MessageSenderEntity,
      timestamp: fields[3] as DateTime,
      isRead: fields[4] as bool,
      type: fields[5] as MessageTypeEntity,
      imagePath: fields[6] as String?,
      imageBytes: fields[7] as Uint8List?,
      characterId: fields[8] as String,
    );
  }

  @override
  void write(BinaryWriter writer, ChatMessageEntity obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.text)
      ..writeByte(2)
      ..write(obj.sender)
      ..writeByte(3)
      ..write(obj.timestamp)
      ..writeByte(4)
      ..write(obj.isRead)
      ..writeByte(5)
      ..write(obj.type)
      ..writeByte(6)
      ..write(obj.imagePath)
      ..writeByte(7)
      ..write(obj.imageBytes)
      ..writeByte(8)
      ..write(obj.characterId);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageEntityAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
